### ISSUE TITLE
编译hadoop提示HMAC_CTX_cleanup找不到

### ISSUE THREAD

**Issue by leesurezen** [kunpengcompute/hackathon#9]
错误：

        [exec] /usr/bin/c++   -g -Wall -O2 -D_REENTRANT -D_GNU_SOURCE -ldl -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -rdynamic CMakeFiles/wordcount-simple.dir/main/native/examples/impl/wordcount-simple.cc.o  -o examples/wordcount-simple libhadooppipes.a libhadooputils.a -lssl -lcrypto -lpthread
     [exec] /usr/bin/ld: libhadooppipes.a(HadoopPipes.cc.o): in function `HadoopPipes::BinaryProtocol::createDigest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
     [exec] /root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/src/main/native/pipes/impl/HadoopPipes.cc:430: undefined reference to `HMAC_CTX_cleanup'
     _**[exec] /usr/bin/ld: /root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/src/main/native/pipes/impl/HadoopPipes.cc:430: undefined reference to `HMAC_CTX_cleanup'**_
     [exec] collect2: error: ld returned 1 exit status
     [exec] make[2]: *** [CMakeFiles/wordcount-simple.dir/build.make:88: examples/wordcount-simple] Error 1
     [exec] make[2]: Leaving directory '/root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/target/native'
     [exec] make[1]: Leaving directory '/root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/target/native'
     [exec] make[1]: *** [CMakeFiles/Makefile2:74: CMakeFiles/wordcount-simple.dir/all] Error 2
     [exec] make: *** [Makefile:84: all] Error 2
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache Hadoop Main ................................. SUCCESS [  0.672 s]
[INFO] Apache Hadoop Build Tools .......................... SUCCESS [  0.665 s]
[INFO] Apache Hadoop Project POM .......................... SUCCESS [  0.595 s]
[INFO] Apache Hadoop Annotations .......................... SUCCESS [  1.939 s]
[INFO] Apache Hadoop Assemblies ........................... SUCCESS [  0.127 s]
[INFO] Apache Hadoop Project Dist POM ..................... SUCCESS [  1.232 s]
[INFO] Apache Hadoop Maven Plugins ........................ SUCCESS [  1.980 s]
[INFO] Apache Hadoop MiniKDC .............................. SUCCESS [  3.082 s]
[INFO] Apache Hadoop Auth ................................. SUCCESS [  3.519 s]
[INFO] Apache Hadoop Auth Examples ........................ SUCCESS [  2.087 s]
[INFO] Apache Hadoop Common ............................... SUCCESS [01:04 min]
[INFO] Apache Hadoop NFS .................................. SUCCESS [  3.113 s]
[INFO] Apache Hadoop KMS .................................. SUCCESS [  9.678 s]
[INFO] Apache Hadoop Common Project ....................... SUCCESS [  0.030 s]
[INFO] Apache Hadoop HDFS ................................. SUCCESS [01:31 min]
[INFO] Apache Hadoop HttpFS ............................... SUCCESS [ 14.307 s]
[INFO] Apache Hadoop HDFS BookKeeper Journal .............. SUCCESS [  3.415 s]
[INFO] Apache Hadoop HDFS-NFS ............................. SUCCESS [  2.763 s]
[INFO] Apache Hadoop HDFS Project ......................... SUCCESS [  0.033 s]
[INFO] hadoop-yarn ........................................ SUCCESS [  0.036 s]
[INFO] hadoop-yarn-api .................................... SUCCESS [ 24.300 s]
[INFO] hadoop-yarn-common ................................. SUCCESS [ 17.716 s]
[INFO] hadoop-yarn-server ................................. SUCCESS [  0.030 s]
[INFO] hadoop-yarn-server-common .......................... SUCCESS [  6.370 s]
[INFO] hadoop-yarn-server-nodemanager ..................... SUCCESS [ 12.284 s]
[INFO] hadoop-yarn-server-web-proxy ....................... SUCCESS [  1.921 s]
[INFO] hadoop-yarn-server-applicationhistoryservice ....... SUCCESS [  3.946 s]
[INFO] hadoop-yarn-server-resourcemanager ................. SUCCESS [ 10.974 s]
[INFO] hadoop-yarn-server-tests ........................... SUCCESS [  2.897 s]
[INFO] hadoop-yarn-client ................................. SUCCESS [  3.457 s]
[INFO] hadoop-yarn-server-sharedcachemanager .............. SUCCESS [  2.098 s]
[INFO] hadoop-yarn-applications ........................... SUCCESS [  0.027 s]
[INFO] hadoop-yarn-applications-distributedshell .......... SUCCESS [  1.438 s]
[INFO] hadoop-yarn-applications-unmanaged-am-launcher ..... SUCCESS [  1.140 s]
[INFO] hadoop-yarn-site ................................... SUCCESS [  0.027 s]
[INFO] hadoop-yarn-registry ............................... SUCCESS [  2.802 s]
[INFO] hadoop-yarn-project ................................ SUCCESS [  3.258 s]
[INFO] hadoop-mapreduce-client ............................ SUCCESS [  0.106 s]
[INFO] hadoop-mapreduce-client-core ....................... SUCCESS [ 11.688 s]
[INFO] hadoop-mapreduce-client-common ..................... SUCCESS [  9.628 s]
[INFO] hadoop-mapreduce-client-shuffle .................... SUCCESS [  2.258 s]
[INFO] hadoop-mapreduce-client-app ........................ SUCCESS [  4.976 s]
[INFO] hadoop-mapreduce-client-hs ......................... SUCCESS [  3.137 s]
[INFO] hadoop-mapreduce-client-jobclient .................. SUCCESS [  3.808 s]
[INFO] hadoop-mapreduce-client-hs-plugins ................. SUCCESS [  1.181 s]
[INFO] Apache Hadoop MapReduce Examples ................... SUCCESS [  3.061 s]
[INFO] hadoop-mapreduce ................................... SUCCESS [  2.335 s]
[INFO] Apache Hadoop MapReduce Streaming .................. SUCCESS [  2.229 s]
[INFO] Apache Hadoop Distributed Copy ..................... SUCCESS [  5.484 s]
[INFO] Apache Hadoop Archives ............................. SUCCESS [  1.331 s]
[INFO] Apache Hadoop Rumen ................................ SUCCESS [  2.905 s]
[INFO] Apache Hadoop Gridmix .............................. SUCCESS [  2.249 s]
[INFO] Apache Hadoop Data Join ............................ SUCCESS [  1.325 s]
[INFO] Apache Hadoop Ant Tasks ............................ SUCCESS [  1.102 s]
[INFO] Apache Hadoop Extras ............................... SUCCESS [  1.545 s]
[INFO] Apache Hadoop Pipes ................................ FAILURE [  7.860 s]
[INFO] Apache Hadoop OpenStack support .................... SKIPPED
[INFO] Apache Hadoop Amazon Web Services support .......... SKIPPED
[INFO] Apache Hadoop Azure support ........................ SKIPPED
[INFO] Apache Hadoop Client ............................... SKIPPED
[INFO] Apache Hadoop Mini-Cluster ......................... SKIPPED
[INFO] Apache Hadoop Scheduler Load Simulator ............. SKIPPED
[INFO] Apache Hadoop Tools Dist ........................... SKIPPED
[INFO] Apache Hadoop Tools ................................ SKIPPED
[INFO] Apache Hadoop Distribution ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:08 min
[INFO] Finished at: 2020-10-23T14:58:33+08:00
[INFO] Final Memory: 237M/1575M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (make) on project hadoop-pipes: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec failonerror="true" dir="/root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/target/native" executable="make">... @ 8:115 in /root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/target/antrun/build-main.xml
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (make) on project hadoop-pipes: An Ant BuildException has occured: exec returned: 2
around Ant part ...<exec failonerror="true" dir="/root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/target/native" executable="make">... @ 8:115 in /root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/target/antrun/build-main.xml
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: exec returned: 2
around Ant part ...<exec failonerror="true" dir="/root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/target/native" executable="make">... @ 8:115 in /root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/target/antrun/build-main.xml
        at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:355)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: /root/lixuezhen/hadoop/hadoop-tools/hadoop-pipes/target/antrun/build-main.xml:8: exec returned: 2
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:646)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:672)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:498)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:327)
        ... 21 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hadoop-pipes

**Comment by leesurezen** [comment]
openssl版本不符合要求，需要安装1.0.x版本的

curl -sL https://www.openssl.org/source/old/1.0.1/openssl-1.0.1u.tar.gz | tar zx -C /opt/ \
&& cd /opt/openssl-1.0.1u \
&& ./config 
&& make \
&& make install
系统中不要安装openssl-devel-1.1版本

**Comment by leesurezen** [comment]
问题解决，关闭
